# Generated by Django 4.1.3 on 2023-01-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_customer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_employee',
        ),
        migrations.AddField(
            model_name='user',
            name='is_contractor',
            field=models.BooleanField(default=False, verbose_name='Is contractor'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_corporator',
            field=models.BooleanField(default=False, verbose_name='Is corporator'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_section_officer',
            field=models.BooleanField(default=False, verbose_name='Is section officer'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_user',
            field=models.BooleanField(default=False, verbose_name='Is user'),
        ),
    ]
