# Generated by Django 3.2.16 on 2023-01-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allotment',
            name='c_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='allotment',
            name='p_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
