# Generated by Django 4.1.3 on 2023-01-18 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_contractor_c_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='c_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
