# Generated by Django 4.1.3 on 2023-01-08 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_is_customer_remove_user_is_employee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pothole',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=500)),
                ('remarks', models.CharField(max_length=500)),
                ('date', models.DateField()),
            ],
        ),
    ]
