# Generated by Django 4.1.3 on 2023-01-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_allotment_c_id_alter_allotment_p_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pothole',
            name='done',
            field=models.BooleanField(default=False, verbose_name='Is done'),
        ),
    ]
