# Generated by Django 4.1.3 on 2023-01-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_pothole_done'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pothole',
            old_name='done',
            new_name='done_cont',
        ),
        migrations.AddField(
            model_name='pothole',
            name='done_corp',
            field=models.BooleanField(default=False, verbose_name='Is done'),
        ),
    ]
