# Generated by Django 4.1.3 on 2023-01-18 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_done_pothole_done_cont_pothole_done_corp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pothole',
            old_name='done_cont',
            new_name='cont_done',
        ),
        migrations.RenameField(
            model_name='pothole',
            old_name='done_corp',
            new_name='corp_done',
        ),
    ]
