# Generated by Django 4.1.3 on 2023-01-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_pothole_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pothole',
            name='img',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
