# Generated by Django 4.1.3 on 2023-01-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_pothole_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pothole',
            name='img',
            field=models.ImageField(default='pothole.jpg', upload_to='images/'),
        ),
    ]
