# Generated by Django 4.1.3 on 2023-01-13 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_pothole_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='pothole',
            name='user',
            field=models.ForeignKey(default='10000', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
