# Generated by Django 4.1.3 on 2023-01-13 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_pothole_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pothole',
            name='user',
        ),
    ]
