# Generated by Django 4.1.3 on 2023-01-13 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_pothole_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pothole',
            name='user',
            field=models.ForeignKey(default='1000', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
