# Generated by Django 4.1.3 on 2023-01-15 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_pothole_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Corporator',
            fields=[
                ('ward_no', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='pothole',
            name='user',
            field=models.ForeignKey(db_column='user_id', default='1000', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Allotment',
            fields=[
                ('p_id', models.ForeignKey(db_column='p_id', default='1000', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.pothole')),
                ('c_id', models.ForeignKey(db_column='c_id', default='1000', on_delete=django.db.models.deletion.CASCADE, to='account.contractor')),
            ],
        ),
        migrations.AddField(
            model_name='pothole',
            name='ward_no',
            field=models.ForeignKey(db_column='ward_no', default='1000', on_delete=django.db.models.deletion.CASCADE, to='account.corporator'),
        ),
    ]
