# Generated by Django 4.1.3 on 2023-01-15 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_contractor_corporator_alter_pothole_user_allotment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allotment',
            name='c_id',
            field=models.ForeignKey(db_column='c_id', on_delete=django.db.models.deletion.CASCADE, to='account.contractor'),
        ),
        migrations.AlterField(
            model_name='allotment',
            name='p_id',
            field=models.ForeignKey(db_column='p_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.pothole'),
        ),
        migrations.AlterField(
            model_name='pothole',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pothole',
            name='ward_no',
            field=models.ForeignKey(db_column='ward_no', on_delete=django.db.models.deletion.CASCADE, to='account.corporator'),
        ),
    ]
