# Generated by Django 4.1.3 on 2023-01-15 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_alter_allotment_c_id_alter_allotment_p_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allotment',
            name='c_id',
            field=models.ForeignKey(db_column='c_id', default='1000', on_delete=django.db.models.deletion.CASCADE, to='account.contractor'),
        ),
        migrations.AlterField(
            model_name='allotment',
            name='p_id',
            field=models.ForeignKey(db_column='p_id', default='1000', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.pothole'),
        ),
        migrations.AlterField(
            model_name='pothole',
            name='user',
            field=models.ForeignKey(db_column='user_id', default='1000', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pothole',
            name='ward_no',
            field=models.ForeignKey(db_column='ward_no', default='1000', on_delete=django.db.models.deletion.CASCADE, to='account.corporator'),
        ),
    ]
