# Generated by Django 4.1.3 on 2023-01-16 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_alter_allotment_c_id_alter_allotment_p_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pothole',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pothole',
            name='ward_no',
            field=models.ForeignKey(db_column='ward_no', on_delete=django.db.models.deletion.CASCADE, to='account.corporator'),
        ),
    ]
